accounts/urls.py
from django.urls import path, include
from . import views #'.' because in same folder

app_name = 'accounts'

urlpatterns = [
    path('',views.signup_view,name='signup'),
    path('login/',views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

exercises/urls.py
from django.urls import path, include
from . import views #'.' because in same folder

app_name = 'exercises'

urlpatterns = [
    path('',views.exercise_list, name = 'list'),
    path('create/', views.exercise_create, name='create'),
    path('<slug:slug>/', views.exercise_detail, name = 'detail'), #for slug of any length and character
]

home/urls.py
from django.urls import path, include
from . import views #'.' because in same folder

app_name = 'home'

urlpatterns = [
    path('home/',views.home_list, name = 'list'),
    #path('create/', views.recipe_create, name='create'),
    #path('<slug:slug>/', views.recipe_detail, name = 'detail'), #for slug of any length and character
]

mysite1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views #'.' because in same folder
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from recipes import views as recipe_views
from exercises import views as exercise_views
from home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('recipes/', include('recipes.urls')),
    path('exercises/', include('exercises.urls')),
    path('home/', include('home.urls')),
    path('about/',views.about, name='about'),
    path('homepage/', views.homepage),
    path('', home_views.home_list, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include
from . import views #'.' because in same folder

app_name = 'recipes'

urlpatterns = [
    path('',views.recipe_list, name = 'list'),
    path('create/', views.recipe_create, name='create'),
    path('<slug:slug>/', views.recipe_detail, name = 'detail'), #for slug of any length and character
]

accounts/models.py
from django.db import models

# Create your models here.

exercises/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Exercise(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    intro = models.CharField(max_length = 200)
    body = models.TextField()
    date = models.DateTimeField(auto_now = True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
        
    def snippet(self):
        return self.intro[:50]

home/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    intro = models.TextField(max_length=300, blank=True)
    ingredients = models.TextField(max_length=300, blank = True)
    directions = models.TextField(max_length=500, blank=True)
    date = models.DateTimeField(default=timezone.now)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.title
        
    def snippet(self):
        return self.intro[:50]

exercises/forms.py
from django import forms
from . import models

# Create your views here.
class CreateExercise(forms.ModelForm):
    class Meta:
        model = models.Exercise
        fields = ['title','slug','intro','body','thumb']

recipes/forms.py
from django import forms
from . import models

# Create your views here.
class CreateRecipe(forms.ModelForm):
    class Meta:
        model = models.Recipe
        fields = ['title','slug','intro','ingredients','directions','thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('home:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})
    
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home:list')

exercises/views.py
from django.shortcuts import render, redirect
from .models import Exercise
from django.http import HttpResponse
from . import forms
from django.contrib.auth.decorators import login_required


# Create your views here.

def exercise_list(request):
    exercises = Exercise.objects.all()
    return render(request, 'exercises/exercise_list.html', {'exercises':exercises})

def exercise_detail(request, slug):
    exercise = Exercise.objects.get(slug=slug)
    return render(request, 'exercises/exercise_detail.html', {'exercise':exercise})

@login_required(login_url="/accounts/login/")
def exercise_create(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        form = forms.CreateExercise(request.POST, request.FILES)
        # create a form instance and populate it with data from the request:
        if form.is_valid():
            #process data and return to exercise list
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('exercises:list')
    else:
        form = forms.CreateExercise()
        return render(request,'exercises/exercise_create.html',{'form':form})

home/views.py
from django.shortcuts import render, redirect
from recipes.models import Recipe
from exercises.models import Exercise
from django.http import HttpResponse



# Create your views here.


def home_list(request):
    recipes = Recipe.objects.all().order_by('date')
    exercises = Exercise.objects.all().order_by('date')
    return render(request, 'home/home_list.html', {'recipes':recipes, 'exercises':exercises})
    

mysite1/views.py
from django.http import HttpResponse
from django.shortcuts import render
from recipes import views as recipe_views
from exercises import views as exercise_views
from recipes.views import recipe_list
from exercises.views import exercise_list
from django.views.generic import TemplateView
from recipes.models import Recipe
from exercises.models import Exercise


def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')
    
 
 
 

recipes/views.py
from django.shortcuts import render, redirect
from .models import Recipe
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def recipe_list(request):
    recipes = Recipe.objects.all().order_by('date')
    return render(request,'recipes/recipe_list.html',{'recipes':recipes})

def recipe_detail(request, slug):
    #return HttpResponse(slug)
    recipe = Recipe.objects.get(slug=slug)
    return render(request, 'recipes/recipe_detail.html', {'recipe':recipe})

@login_required(login_url="/accounts/login/")
def recipe_create(request):
    if request.method == 'POST':
        form = forms.CreateRecipe(request.POST, request.FILES)
        if form.is_valid():
            #save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('recipes:list')
    else:
        form = forms.CreateRecipe()
    return render(request,'recipes/recipe_create.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1 class="big">Enter for the good stuff!</h1>
    <h3>Login!</h3>
    <form class="site-form"action="{% url 'accounts:login' %}"method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login"/>
    </form>
    <form class="signup"action="{% url 'accounts:signup' %}">
        <button type="submit">Signup!</button>
    </form>
    
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1 class="big">Join the crew now!</h1>
    <h3>Sign Up Here!</h3>
    <form class="site-form"action="{% url 'accounts:signup' %}"method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

exercises/templates/exercises/exercise_create.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "create-exercise">
        <h2> Post your favorite exercise routines here! </h2>
            <form class="site-form" action="{% url 'exercises:create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <input type="submit" value="Create">
            </form>
        </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

exercises/templates/exercises/exercise_detail.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "recipe-detail">
        <div class = "recipe">
            <img src = "{{exercise.thumb.url}}" width="200" height="auto">
            <h2>{{exercise.title}}</h2>
            <p>{{exercise.date}}</p>
            <p>{{exercise.intro}}</p>
            <p>{{exercise.body}}</p>
        </div>
    </div>
{% endblock %}

exercises/templates/exercises/exercise_list.html
{% extends 'base_layout.html'%}

{% block content %}

    <h1>Lets get movin'!</h1>
    <div class = "recipes">
        {% for exercise in exercises %}
        <div class="recipe">
                <h2><a href="{% url 'exercises:detail' slug=exercise.slug %} ">{{exercise.title}}</a></h2>
                <p>{{exercise.date}}</p>
                <p class="author">exercise by {{exercise.author.username}}</p>
                <p>{{exercise.snippet}}</p>
           </div>
        {% endfor %}
    </div>
{% endblock %}

home/templates/home/home_create.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "create-recipe">
        <h2> Post your recipe here! </h2>
        <form class="site-form" action="{% url 'recipes:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>

{% endblock %}

home/templates/home/home_detail.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "recipe-detail">
        <div class = "recipe">
            <img src = "{{recipe.thumb.url}}" width="200" height="auto">
            <h2>{{recipe.title}}</h2>
            <p>{{recipe.date}}</p>
            <p>{{recipe.snippet}}</p>
            <p>{{recipe.ingredients}}</p>
            <p>{{recipe.directions}}</p>
        </div>
    </div>
{% endblock %}

home/templates/home/home_list.html
{% extends 'base_layout.html'%}
{% block content %}

   <h1>What's New!</h1>
          <div class = "home">
              {% for recipe in recipes %}
                  <div class = "recipe">
                      <h2><a href = "{% url 'recipes:detail' slug=recipe.slug %}">{{recipe.title}}</a></h2>
                      <p>{{recipe.date}}</p>
                      <p class="author">recipe by {{recipe.author.username}}</p>
                      <p>{{recipe.snippet}}</p>
                  </div>
              {% endfor %}
              {% for exercise in exercises %}
                <div class = "recipe">
                  <h2><a href="{% url 'exercises:detail' slug=exercise.slug %}">{{exercise.title}}</a></h2>
                  <p>{{exercise.date}}</p>
                  <p class="author">exercise by {{exercise.author.username}}</p>
                  <p>{{exercise.snippet}}</p>
                </div>
              {% endfor %}
          </div>

{% endblock %}

recipes/templates/recipes/recipe_create.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "create-recipe">
        <h2> Post your recipe here! </h2>
        <form class="site-form" action="{% url 'recipes:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>

{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class = "recipe-detail">
        <div class = "recipe">
            <img src = "{{recipe.thumb.url}}" width="200" height="auto">
            <h2>{{recipe.title}}</h2>
            <p>{{recipe.date}}</p>
            <p>{{recipe.snippet}}</p>
            <p>{{recipe.ingredients}}</p>
            <p>{{recipe.directions}}</p>
        </div>
    </div>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends 'base_layout.html'%}

{% block content %}

        <h1>Let's get cookin'!</h1>
        <div class = "recipes">
            {% for recipe in recipes %}
                <div class = "recipe">
                    <h2><a href = "{% url 'recipes:detail' slug=recipe.slug %}">{{recipe.title}}</a></h2>
                    <p>{{recipe.date}}</p>
                    <p class="author">recipe by {{recipe.author.username}}</p>
                    <p>{{recipe.snippet}}</p>
                </div>
            {% endfor %}
        </div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html'%}
   
{% block content %}
   <head>
       <meta charset = "utf-8">
       <title>About</title>
   </head>
   <body>
       <h1>About me!</h1>
       <p>I love all things health and fitness, and want a space to share workouts and clean eating recipes!</p>
       
   </body>
{% endblock %}

templates/base_layout.html
{% load static from static %}

<html>
    <head>
        <meta charset = "utf-8">
        <title>Recipes</title>
        <link rel = "stylesheet" href = "{% static 'styles.css' %}">
    </head>
    <body>
        <div class="navbar">
                <a href="{% url 'home:list' %}">Home</a>
                <a href="{% url 'about' %}">About</a>
                <div class="dropdown">
                    <button class="dropbtn">Recipe Index</button>
                    <div class="dropdown-content">
                        <a href="{% url 'recipes:list' %}"class="highlight">Recipe List</a>
                        <a href="{% url 'recipes:create' %}"class="highlight">Submit your Recipe Here!</a></div></div>
                <div class="dropdown">
                    <button class="dropbtn">Fitness Index</button>
                    <div class="dropdown-content">
                         <a href="{% url 'exercises:list' %}"class="highlight">Fitness Index</a>
                         <a href="{% url 'exercises:create' %}"class="highlight">Submit Exercises Here!</a>
                    </div>
                </div>
           
            <div class="login-container">
               {% if user.is_authenticated %}
               <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
               </form>
               
               {% else %}
               <div class="logsign">
               <form class="login-link"action="{% url 'accounts:signup' %}">
                   <button type="submit">Signup!</button>
               </form></div>
               <div class="logsign">
                   <form class="login-link"action="{% url 'accounts:login' %}"method="post">
                       {% csrf_token %}
                       <button type="submit">Login</button>
                   </form></div>
               {% endif %}
            </div>
        </div>
       <div class ="logo">
           <h1><a href = "{% url 'home' %}"><img src = "{% static 'Logo.png' %}"/></a></h1>
        </div>
        <div class="wrapper">
           {% block content %}
           {% endblock %}
       </div>
    </body>
</html>

templates/homepage.html
{% extends 'base_layout.html'%}
{% block content %}

   <h1>What's New!</h1>
          <div class = "home">
              {% for recipe in recipes %}
                  <div class = "recipe">
                      <h2><a href = "{% url 'recipes:detail' slug=recipe.slug %}">{{recipe.title}}</a></h2>
                      <p>{{recipe.date}}</p>
                      <p class="author">recipe by {{recipe.author.username}}</p>
                      <p>{{recipe.snippet}}</p>
                  </div>
              {% endfor %}
              {% for exercise in exercises %}
                  <h2><a href="exercise_detail.html">Post your favorite workouts/exercises here!</a></h2>
                  <p>{{exercise.title}}</p>
                  <p>{{exercise.date}}</p>
                  <p class="author">exercise by {{exercise.author.username}}</p>
                  <p>{{exercise.snippet}}</p>
              {% endfor %}
          </div>

{% endblock %}